name: Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  docfx:
    name: "Run DocFX tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install --require-hashes -r .kokoro/docs/docker/requirements.txt
    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: "8.0"
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer --no-interaction --no-ansi --no-progress update
    - name: Install phpDocumentor
      run: |
        wget -O /usr/local/bin/phpdoc "https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar" \
          && chmod +x /usr/local/bin/phpdoc
    - name: Run DocFX Unit Test Suite
      run: vendor/bin/phpunit -c dev/phpunit-docfx.xml.dist
    - name: Run Docs Generator (Dry Run)
      run: bash .kokoro/docs/publish.sh
